# Generated by Django 2.1 on 2018-09-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cargo',
            field=models.CharField(blank='True', max_length=120, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank='True', max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='empresa',
            field=models.CharField(blank='True', max_length=50, verbose_name='Empresa'),
        ),
    ]
